### PR TITLE
Work on TNW page clone

### PR DESCRIPTION
**Pull request by jabichris**
#### What does this PR do?
It is for a learning purpose where we created a clone of the TNW page.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI team :clap:. Good job here but we need to address the following :arrow_double_down:**

1. The title of your README is for another project.

2. Add a better description of the project in the README

3. TNW Logo is missing on large screens

4. The three columns in the Latest News section should fill up the page width, no space should be left on the right. Also, adjust your font size appropriately.
image

5. Latest News section is distorted on small screens.
image

6.The Latest Funding section should be aligned 4 per row on large screens.


7. Let us have this title and the arrow fall on the same line.

image

8. Text(prices) for Latest Deals section on small screens should be properly aligned.
image


9. Some sections of the page require left and right margins for small screen sizes. Look through the page and adjust them accordingly.

10. Use anchor tags for all links on the page.

11. Your media queries should target the following:
small screens - max-width around 700
medium screens - max-width around 1000
large screens - min-width over 1000


_**Kindly address these issues and submit another code review request.**_

**Cheers:smile:**

**Status: Changes requested**

**Review by Forison — CHANGES_REQUESTED** [review]
## Status Require Changes🛑
# Hi Team🙋‍♂️,
Impressive!! the page looks good, but we can make it better. Here are a few changes we can make to get this approved.
* [ ] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] Let us make the page better by making some adjustment
This our page at SMall screen size (LATES NEWS SECTION)👇
Screenshot from 2020-01-28 18-40-54
This is the original page at small screen size👇
Screenshot from 2020-01-28 18-40-31
Some overflowing text is causing horizontal scroll👇

Screenshot from 2020-01-28 18-41-36
Let fix these issues

* [ ] As mentioned in the previous review, Your readme is not in line with this project, let us fix it. You can also describe the project in a few lines in your readme. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
##### THAT IS KINDLY MAKE THESE CHANGES AND SUBMIT PROJECT FOR REVIEW
### Happy coding🙂
### Addo Forison

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Hi!

It's almost there, but still missing some small requirements 😣.

- [ ] The title of your README is for another project (mentioned by @mosesogwo).
- [ ] On small screen overflowing text is causing horizontal scroll (mentioned by @Forison).
- [ ] On large screen on the top 3 articles section the TWN logo at the top left corner of the row is missing:
image

You are doing great, keep up the good work 🚀!

Status: **Request changes**

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1:good!
Here are things that you still need to change:
* [ ] On large screen on the top 3 articles section the TNW logo should be at the top left corner of the row. What you have is an image in center, it should look like on original website.
* [ ] Tablet version should look like original wesite:
* Your version:
image
* Original:
image
* [ ] Please take a look at how sections are aligned in original website, and try to fix yours accordingly:
* Your version (just example to show difference between two sections, you need to take closer look at all sections in your project and align them properly one after another ):
image
* Original:
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Hi! It's getting there 🥇.

Huge respect for all the effort and hard work you have put into this, it's showing on the final result.

There are still some issues on the medium size, take a look at this screenshot and notice the resolution I'm using so you can reproduce it and fix it:
image

Status: **Request changes**

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :airplane: 

Congratulations Team for putting in much effort to this project. Your project looks great and i will have to approve it. :+1:  But before you merge to master i will request a change for you. Comment below:
- Let us correct the heights. 
Original
op

Your version
od

Good luck with your next project :slightly_smiling_face: 
Happy coding :computer:

**Pull request merged**
